export const VLANG_ADD_LINK = "VLANG_ADD_LINK";
export const VLANG_REMOVE_LINK = "VLANG_REMOVE_LINK";
export const VLANG_ADD_NODE = "VLANG_ADD_NODE";
export const VLANG_REMOVE_NODE = "VLANG_REMOVE_NODE";
export const VLANG_UPDATE_NODE_POSITION = "VLANG_UPDATE_NODE_POSITION";


export const LAYER_NODE = "LAYER_NODE";
export const ADDITION_NODE = "ADD_NODE";
export const MULTIPLICATION_NODE = "MULTIPLICATION_NODE";
export const AND_NODE = "ADD_NODE";
export const OR_NODE = "OR_NODE";
export const NOT_NODE = "NOT_NODE";